package com.weibo.talentintroduction.common.domain

enum class ConversationStatus {
    NEW,
    INTRO_SENT,
    WAITING_REPLY,
    INTEREST_CONFIRMED,
    QA_AUTO_REPLIED,
    MEETING_SCHEDULING,
    MEETING_INVITATION_SENT,
    WAITING_MEETING_CONFIRMATION,
    MATERIALS_PARTIAL,
    MATERIALS_RECEIVED,
    MANUAL_HANDOFF,
    MANUAL_REVIEW,
    CLOSED
}
