package com.weibo.talentintroduction.simulator.service

data class SimulatorPreset(
    val key: String,
    val label: String,
    val subject: String,
    val body: String,
    val expectedIntent: String,
    val expectedAutoAction: String,
    val expectedNewStatus: String,
    val createsMeetingSchedule: Boolean = false,
    val requiresAttachment: Boolean = false
)

val SIMULATOR_PRESETS = listOf(
    SimulatorPreset("INTERESTED", "感兴趣", "Re: Introduction",
        "Thanks for reaching out. I am interested and happy to discuss.",
        "INTERESTED", "SEND_MEETING_INVITATION", "MEETING_SCHEDULING"),
    SimulatorPreset("ASK_MORE_INFO", "询问详情", "Re: Introduction",
        "Could you tell me more details about the program?",
        "ASK_MORE_INFO", "QA", "QA_AUTO_REPLIED"),
    SimulatorPreset("ASK_PROCESS", "询问流程", "Re: Introduction",
        "What is the application timeline and deadline?",
        "ASK_PROCESS", "QA", "QA_AUTO_REPLIED"),
    SimulatorPreset("ASK_REMOTE", "远程/兼职", "Re: Introduction",
        "Can this position be remote or part-time?",
        "ASK_REMOTE_PART_TIME", "QA", "QA_AUTO_REPLIED"),
    SimulatorPreset("ASK_FUNDING", "资金/工资", "Re: Introduction",
        "Who is funding the salary and how are fees handled?",
        "ASK_FUNDING", "MANUAL_REVIEW", "MANUAL_HANDOFF"),
    SimulatorPreset("ASK_CONFIDENTIALITY", "保密/IP", "Re: Introduction",
        "My employer has an IP conflict clause, is this confidential?",
        "ASK_CONFIDENTIALITY", "MANUAL_REVIEW", "MANUAL_HANDOFF"),
    SimulatorPreset("MEETING_TIME", "提供会议时间", "Re: Introduction",
        "I am available on Tuesday 10am via Zoom.",
        "MEETING_TIME_PROVIDED", "MANUAL_REVIEW", "MANUAL_HANDOFF",
        createsMeetingSchedule = true),
    SimulatorPreset("MEETING_REQUEST", "请求安排会议", "Re: Introduction",
        "Could we set up a meeting next week?",
        "MEETING_REQUESTED", "MANUAL_REVIEW", "MANUAL_HANDOFF",
        createsMeetingSchedule = true),
    SimulatorPreset("CV_ATTACHED", "CV 附件", "Re: Introduction - CV",
        "Please find attached my CV.",
        "CV_ATTACHED", "MANUAL_REVIEW", "MANUAL_HANDOFF",
        requiresAttachment = true),
    SimulatorPreset("DOCS_ATTACHED", "其它材料附件", "Re: Introduction - Documents",
        "Attached you will find my passport and degree certificate.",
        "DOCS_ATTACHED", "MANUAL_REVIEW", "MANUAL_HANDOFF",
        requiresAttachment = true),
    SimulatorPreset("NOT_INTERESTED", "拒绝", "Re: Introduction",
        "Please remove me from your list, I am not interested.",
        "NOT_INTERESTED", "CLOSE", "MANUAL_HANDOFF"),
    SimulatorPreset("QA_MISS", "QA 未命中", "Re: Introduction",
        "Random unrelated text about the weather today in London.",
        "UNKNOWN", "QA", "MANUAL_HANDOFF"),
    SimulatorPreset("EMPTY", "空回复", "Re: Introduction",
        "",
        "UNKNOWN", "MANUAL_REVIEW", "MANUAL_HANDOFF")
)
